import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

/**
 * A plugin bundle ships **no CSS of its own** — `scripts/makePluginConfig.mjs`
 * builds a single ESM file and nothing else, and the UI is styled entirely by
 * the host app's already-compiled Tailwind sheet. That sheet is generated by
 * scanning the host's own `src/**` (`tailwind.config.js` → `content`), which
 * never includes this repo, so a class only ever written here exists as text
 * in the DOM with no rule behind it.
 *
 * **Arbitrary values** (`h-[68vh]`, `max-h-[70vh]`, …) are the ones no safelist
 * can ever rescue: each is a distinct rule, emitted only if some host file
 * happens to spell it character-for-character. `h-[68vh]` and
 * `max-h-[calc(100vh-13rem)]` on the container log dialog did not, so its log
 * box fell back to `height: auto`, grew with every line that streamed in, and
 * ran the dialog off both ends of the screen with its own toolbar out of reach.
 *
 * Sizing and layout is where a missing rule turns into an unusable window
 * rather than a cosmetic nudge, so those prefixes are gated here: use an
 * inline `style` instead, which no build step can drop.
 *
 * **This is only the half that can be checked offline.** Plain named utilities
 * go missing the same way — `bottom-3`, `py-5`, `h-64`, `m-4` and
 * `translate-x-full` all had no rule, while `max-h-64` right beside `h-64`
 * did. The host now safelists the common scales
 * (`src/styles/plugin-utilities.css` there), but a plugin installs into
 * whatever host the user already has, so run the complete check against a real
 * host build: `node scripts/check-host-classes.mjs <host>/dist/assets/*.css`.
 */

const GATED_PREFIXES = [
  'h', 'w', 'size', 'max-h', 'max-w', 'min-h', 'min-w',
  'basis', 'grid-cols', 'grid-rows', 'inset', 'top', 'right', 'bottom', 'left',
];

/**
 * Arbitrary sizing classes verified to exist in the host's compiled sheet.
 * Add one only after finding it there with `scripts/check-host-classes.mjs`
 * against the OLDEST host release this plugin still supports — and prefer an
 * inline style, which needs no entry here and cannot go stale.
 */
const ALLOWED = new Set<string>([]);

const UI_DIR = import.meta.dirname;

function sources(dir: string, out: string[] = []): string[] {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name === 'node_modules' || e.name === 'dist') continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) sources(p, out);
    else if (/\.tsx?$/.test(p) && !/\.test\.tsx?$/.test(p)) out.push(p);
  }
  return out;
}

/** Comments name these classes when explaining why they are avoided — scanning
 *  them would flag the explanation itself. */
function stripComments(src: string): string {
  return src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');
}

/** `md:hover:max-h-[70vh]` → `max-h-[70vh]`; anything not a gated utility → null. */
export function gatedArbitraryClass(token: string): string | null {
  const bare = token.replace(/^(?:[a-z-]+:)+/, '').replace(/^-/, '');
  const m = /^([a-z-]+)-\[[^\]]+\]$/.exec(bare);
  return m && GATED_PREFIXES.includes(m[1]) ? bare : null;
}

describe('plugin classes the host stylesheet may not contain', () => {
  it('uses no un-allowlisted arbitrary sizing/layout class', () => {
    const offenders: string[] = [];
    for (const file of sources(UI_DIR)) {
      const src = stripComments(fs.readFileSync(file, 'utf8'));
      src.split('\n').forEach((line, i) => {
        // Matched, not split: `max-h-[calc(100vh-13rem)]` and
        // `grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)]` contain parentheses and
        // commas, so splitting on those tore them into fragments that no
        // longer looked like classes — and the arbitrary values most worth
        // catching are exactly the ones with a function call inside.
        for (const [token] of line.matchAll(/[^\s"'`{}]+/g)) {
          const cls = gatedArbitraryClass(token);
          if (cls && !ALLOWED.has(cls)) {
            offenders.push(`${path.basename(file)}:${i + 1}  ${cls}`);
          }
        }
      });
    }
    expect(
      offenders,
      'These have no rule in the host app\'s compiled Tailwind sheet unless a host '
      + 'src/** file spells them identically. Use an inline `style` instead, or add '
      + 'to ALLOWED once verified against the host.',
    ).toEqual([]);
  });

  it('recognises a gated class behind variants', () => {
    expect(gatedArbitraryClass('h-[68vh]')).toBe('h-[68vh]');
    expect(gatedArbitraryClass('sm:max-h-[calc(100vh-13rem)]')).toBe('max-h-[calc(100vh-13rem)]');
    expect(gatedArbitraryClass('text-[11px]')).toBeNull();
    expect(gatedArbitraryClass('flex')).toBeNull();
  });

  it('keeps a bracketed value whole through a function call', () => {
    // The tokenizer used to split on parentheses and commas, which tore these
    // two apart and let them through — and they are the shape most worth
    // catching, since a value with a call in it is never in a host file.
    const line = '<div className="grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)] max-h-[calc(100vh-13rem)]" />';
    const found = [...line.matchAll(/[^\s"'`{}]+/g)]
      .map(([t]) => gatedArbitraryClass(t))
      .filter(Boolean);
    expect(found).toEqual([
      'grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)]',
      'max-h-[calc(100vh-13rem)]',
    ]);
  });
});
